/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as DevolucionesRouteImport } from './routes/devoluciones'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CambiosRouteImport } from './routes/cambios'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesRoute = DevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosRoute = CambiosRouteImport.update({
  id: '/cambios',
  path: '/cambios',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambios': typeof CambiosRoute
  '/cookies': typeof CookiesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambios': typeof CambiosRoute
  '/cookies': typeof CookiesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambios': typeof CambiosRoute
  '/cookies': typeof CookiesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/cambios'
    | '/cookies'
    | '/devoluciones'
    | '/envios'
    | '/privacidad'
    | '/sobre'
    | '/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/cambios'
    | '/cookies'
    | '/devoluciones'
    | '/envios'
    | '/privacidad'
    | '/sobre'
    | '/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/cambios'
    | '/cookies'
    | '/devoluciones'
    | '/envios'
    | '/privacidad'
    | '/sobre'
    | '/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CambiosRoute: typeof CambiosRoute
  CookiesRoute: typeof CookiesRoute
  DevolucionesRoute: typeof DevolucionesRoute
  EnviosRoute: typeof EnviosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SobreRoute: typeof SobreRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones': {
      id: '/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof DevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios': {
      id: '/cambios'
      path: '/cambios'
      fullPath: '/cambios'
      preLoaderRoute: typeof CambiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CambiosRoute: CambiosRoute,
  CookiesRoute: CookiesRoute,
  DevolucionesRoute: DevolucionesRoute,
  EnviosRoute: EnviosRoute,
  PrivacidadRoute: PrivacidadRoute,
  SobreRoute: SobreRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
